### ISSUE TITLE
Tarea a realizar en la semana 2 de AdoptaUnJunior. Añadir al menú de opciones una que permita abrir un curriculumm en pdf.

### ISSUE THREAD

**Issue by spinelf** [spinelf/AdoptadmeXFa#1]
## Resumen funcionalidad a implementar

Añadir una opción en el menú de opciones que nos permita abrir el curriculum y y visualizarlo en pdf. Para ello se deberá crear adicionalmente un función de abrir fichero en una ruta determinada. 

<a href="https://github.com/spinelf/AdoptadmeXFa/blob/main/Documentacion_issue.md">Documentación para desarrollo de la Issue</a>

**Comment by Valnarg** [comment]
Hola que tal, no se si esto es lo que tenias en mente, pero leyendo tu presentacion, se me ocurrio esto:

1. En el menu de opciones de tu presentacion añado la opcion 4:

print("4. Ver mi currículum en PDF")

2. Añado una funcion para abrir curriculum en PDF:

import webbrowser

def abrir_curriculum():

    # Ruta del archivo PDF
    ruta_pdf = "ruta/del/curriculum.pdf"  # Ubicación de tu archivo PDF
    
    # Abre el archivo PDF con el visor predeterminado del sistema
    webbrowser.open(ruta_pdf)

3.En tu funcion llamarOpcionCorrecta añado la siguiente opcion:

 elif opcion == 4:  # Esta opción abre el currículum en PDF
        os.system("cls")
        encabezado()
        print("")
        abrir_curriculum()
        print("")
        input("Pulse Enter para continuar  ")
        os.system("cls")  

Creo que con esto deberia funcionar, habria que cambiar la ruta del archivo por la ruta donde tu almacenes el PDF, pero estaria listo.

Espero haber ayudado 😄

**Comment by spinelf** [comment]
@Valnarg 
Muchas gracias Jorge, si puedes ayudarme, te lo agradecería mucho, para realizar lo que piden en la semana dos tendrías que hacer un fork, crear una rama, meter el código que me has propuesto, ver si funciona correctamente, actualizar el main con tus cambios  y por ultimo solicitar un pull request para que yo lo acepte y se incorporen mis cambios al repositorio.

**Comment by Valnarg** [comment]
Claro que sí, te ayudo encantado. 😊 

Esta tarde me pongo a ello y te mando los cambios

**Comment by Valnarg** [comment]
Ya lo deberías tener listo 🙂

**Comment by spinelf** [comment]
Muchas gracias por tu contribución, has sido de gran ayuda.  Estaba todo muy claro 🥇  :Si necesitas algo ya me dices a ver si te puedo ayudar 💯

**Comment by Valnarg** [comment]
@spinelf te agradecería si le echas un vistazo a mi issue, he cambiado la que tenía por otra más razonable,haber si puedo completar yo también  la semana 2 😄.

Muchas gracias de antemano.
